name: nf-core-tpp
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
#  - openms=2.4.0
  - thermorawfileparser=1.3.3
# removed as too old
#  - tpp=5.0.0
  - comet-ms=2019014
  - r-progress=1.2.2
  - r-xml=3.99-0.8
  - r-stringi=1.7.6
  - pyteomics=4.4.0
